package net.amathboi.mi84mod.client.calculator.input

/** Stable identities for the 50 physical keys shown on the calculator texture. */
enum class CalculatorKey(val primaryLegend: String) {
    Y_EQUALS("Y="),
    WINDOW("Window"),
    ZOOM("Zoom"),
    TRACE("Trace"),
    GRAPH("Graph"),
    SECOND("2nd"),
    MODE("Mode"),
    DELETE("Del"),
    DOWN("Down"),
    UP("Up"),
    ALPHA("Alpha"),
    VARIABLE("X,T,θ,n"),
    STAT("Stat"),
    LEFT("Left"),
    RIGHT("Right"),
    MATH("Math"),
    APPS("Apps"),
    PROGRAM("Prgm"),
    VARS("Vars"),
    CLEAR("Clear"),
    RECIPROCAL("x⁻¹"),
    SIN("sin"),
    COS("cos"),
    TAN("tan"),
    POWER("^"),
    SQUARE("x²"),
    COMMA(","),
    OPEN_PARENTHESIS("("),
    CLOSE_PARENTHESIS(")"),
    DIVIDE("÷"),
    LOG("log"),
    DIGIT_7("7"),
    DIGIT_8("8"),
    DIGIT_9("9"),
    MULTIPLY("×"),
    LN("ln"),
    DIGIT_4("4"),
    DIGIT_5("5"),
    DIGIT_6("6"),
    SUBTRACT("−"),
    STORE("sto→"),
    DIGIT_1("1"),
    DIGIT_2("2"),
    DIGIT_3("3"),
    ADD("+"),
    ON("On"),
    DIGIT_0("0"),
    DECIMAL("."),
    NEGATIVE("(−)"),
    ENTER("Enter")
}

/** A calculator artwork key clicked with the mouse. */
data class CalculatorInputEvent(val key: CalculatorKey)
